
import React from "react";
import Link from "next/link";
import ContactUs from "@/components/ContactUs";

export const metadata = {
  title: "Tradeswift - Contact Us",
  description: "Generated by Tradeswift - Contact Us",
};
const ContactPage = () => {
  return (
    <div className="min-h-screen">
      <div className="h-80" style={{backgroundImage: "url(https://i.ibb.co/KVVxYts/sub-Banner.png)",backgroundRepeat:"no-repeat",backgroundSize:'cover',backgroundPosition:'center'}}>
        <div className="container h-full flex flex-col gap-y-4 justify-center mx-auto px-4 ">
          <h1 className="text-5xl font-bold">Contact Us</h1>
          <p className="text-lg font-semibold"><Link className="text-[#00D094]" href='/'>Home</Link> / Contact Us</p>
        </div>
      </div>
      <div className="container mx-auto px-2">
        <ContactUs></ContactUs>
      </div>
    </div>
  );
};

export default ContactPage;
